# Generated by Django 2.2.4 on 2019-08-29 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.TextField(blank=True, db_index=True)),
                ('dis_adv', models.TextField(blank=True, db_index=True)),
                ('comment', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('desc', models.TextField(blank=True, db_index=True)),
                ('price', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(db_index=True, default='хит', max_length=50)),
                ('picture', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='pictures/')),
                ('date_public', models.DateField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='products', to='items.CommentProduct')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
