# Generated by Django 2.2.4 on 2019-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_id',
        ),
        migrations.AddField(
            model_name='basket',
            name='product_to',
            field=models.TextField(blank=True, db_index=True, unique=True),
        ),
    ]
