# Generated by Django 2.2.4 on 2019-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190924_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product_to',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
