# Generated by Django 2.2.11 on 2020-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200329_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='pictures/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(db_index=True, default='хит', verbose_name='Статус товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название товара'),
        ),
    ]
