# Generated by Django 2.2.11 on 2020-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200330_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='adv',
            field=models.TextField(blank=True, db_index=True, verbose_name='Достоинства'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='comment',
            field=models.TextField(blank=True, db_index=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='dis_adv',
            field=models.TextField(blank=True, db_index=True, verbose_name='Недостатки'),
        ),
    ]
