# Generated by Django 2.2.11 on 2020-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20200401_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_public',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
