# Generated by Django 2.2.11 on 2020-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20200401_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_public',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
